### ISSUE TITLE
ApplicationExceptionFilter return 500 on nest version 4.6.5

### ISSUE THREAD

**Issue by Dominic-Preap** [chanlito/nestjs-extensions#3]
On version 4.6.5 updates say:
- common: `HttpException` extends `Error`
- microservices: `RpcException` extends `Error`
- websockets: `WsException` extends `Error`

In your code base by checking `instanceof ` Error will make every exception to status 500
```js
if (err instanceof Error) {
      console.error(errTitle, err);
      const statusCode = HttpStatus.INTERNAL_SERVER_ERROR;
      res.status(statusCode).json({
        statusCode,
        message: 'Internal Server Error'
      });
    }
```

**Comment by chanlito** [comment]
fixed
